const PASS_PERCENT = 90;
const QUESTIONS_PER_NODE = 10;
const TESTS_PER_MODULE = 5;
const LESSON_COST = 20;
const DAILY_CREDITS = 20;
const XP_PER_CORRECT = 10;
const XP_DOUBLE_COMBO_INTERVAL = 4;
const SHOP_XP_COST = 200;
const SHOP_CREDITS_GAIN = 10;
const COMBO_REWARD_MIN = 1;
const COMBO_REWARD_MAX = 4;

const PATH = [
  { id: "node_1", number: 1, title: "Chanson : A Maré Tá Cheia", skill: "chants", kind: "lesson", songId: "song_mare_cheia" },
  { id: "node_5", number: 2, title: "Culture et histoire", skill: "culture", kind: "lesson" },
  { id: "node_2", number: 3, title: "Chanson : Folha Seca", skill: "chants", kind: "lesson", songId: "song_folha_seca" },
  { id: "node_6", number: 4, title: "Portugais du capoeiriste", skill: "portugais", kind: "lesson" },
  { id: "node_3", number: 5, title: "Chanson : Oi Sim Sim Sim", skill: "chants", kind: "lesson", songId: "song_oi_sim_sim" },
  { id: "eval_1", number: "★", title: "Évaluation 1", kind: "evaluation", includes: ["node_1", "node_5", "node_2", "node_6", "node_3"] },

  { id: "node_7", number: 6, title: "Instruments de musique", skill: "berimbau", kind: "lesson" },
  { id: "node_4", number: 7, title: "Chanson : ABC", skill: "chants", kind: "lesson", songId: "song_abc" },
  { id: "node_8", number: 8, title: "Mouvements et techniques", skill: "techniques", kind: "lesson", testsRequired: 8 },
  { id: "node_9", number: 9, title: "Rythmes du berimbau", skill: "berimbau", kind: "lesson" },
  { id: "node_10", number: 10, title: "Révision mixte", skill: "mixed", kind: "review" },
  { id: "eval_2", number: "★", title: "Évaluation 2", kind: "evaluation", includes: ["node_7", "node_4", "node_8", "node_9", "node_10"] }
];

const SONGS = [
  {
    id: "song_mare_cheia",
    title: "A Maré Tá Cheia",
    focus: "Refrain, montée et descente",
    lines: [
      "A maré 'tá cheia, ioió",
      "A maré 'tá cheia, iaiá!",
      "A maré 'tá cheia, ioió,",
      "A maré 'tá cheia, iaiá!",
      "A maré subiu",
      "Sobe maré,",
      "A maré desceu",
      "Desce maré,",
      "Ô maré é de maré",
      "Vou pra Ilha de Maré!",
      "Olha o peixe pulou na maré!"
    ],
    note: "Retenir le mouvement aide: maré subiu = sobe, maré desceu = desce."
  },
  {
    id: "song_folha_seca",
    title: "Folha Seca",
    focus: "Réponse du chœur et mandinga",
    lines: [
      "Eu pisei na folha seca",
      "E ouvi fazer: chuê chua",
      "Chuê chuê chuê chua",
      "Ouvi fazer, chuê chua",
      "Quem não pode com mandinga, não carrega patuá",
      "Quem não pode com Besouro, não carrega Mangangá",
      "Você disse que dá no nego, no nego você não dá",
      "Na casa do batuqueiro quero ver tu mandingar",
      "Joga nego para cima",
      "Deixa o nego invadiar",
      "O guerreiro senzalero, essa cobra vai fumar"
    ],
    note: "La ligne 'chuê chua' fonctionne comme une réponse facile à reprendre."
  },
  {
    id: "song_oi_sim_sim",
    title: "Oi Sim Sim Sim",
    focus: "Réponse oui/non",
    lines: [
      "Oi sim sim sim",
      "Oi não não não",
      "Mas hoje tem amanhã não",
      "Mas se meu mestre disse que sim",
      "Quero ver quem diz que não",
      "Olha a pisada de lampião"
    ],
    note: "Le refrain alterne deux réponses très courtes: sim et não."
  },
  {
    id: "song_abc",
    title: "ABC",
    focus: "Associer lettres et mots de capoeira",
    lines: [
      "É o A, é o B,",
      "É o A, é o B, é o C",
      "É o A de au, é o B de berimbau,",
      "É o C de capoeira",
      "Quero aprender, yayá",
      "Eu não sei ler, yayá",
      "Quero aprender, yayá",
      "É o ABC, yayá"
    ],
    note: "Le chant relie A, B, C à aú, berimbau et capoeira."
  },
  {
    id: "song_viva_meu_mestre",
    title: "Iê viva meu mestre",
    focus: "Louvação et respect",
    lines: ["Iê viva meu mestre", "Iê viva meu mestre, camará", "Iê quem me ensinou", "Iê quem me ensinou, camará"],
    note: "On travaille la structure appel puis réponse."
  },
  {
    id: "song_ai_aide",
    title: "Ai ai Aidê",
    focus: "Refrain expressif",
    lines: ["Ai ai Aidê", "Joga bonito que eu quero ver", "Ai ai Aidê"],
    note: "Un refrain simple pour oser chanter fort."
  },
  {
    id: "song_dona_maria",
    title: "Dona Maria do Camboatá",
    focus: "Nom propre et chœur",
    lines: ["Dona Maria do Camboatá", "Ela chega na roda", "Para ver capoeira jogar"],
    note: "Repère le titre puis les mots qui reviennent."
  },
  {
    id: "song_zum_zum_zum",
    title: "Zum zum zum",
    focus: "Rythme et répétition",
    lines: ["Zum, zum, zum", "Capoeira mata um", "Zum, zum, zum"],
    note: "La répétition aide à garder le tempo."
  },
  {
    id: "song_bahia",
    title: "Bahia de todos os santos",
    focus: "Culture et lieu",
    lines: ["Bahia de todos os santos", "Terra de muita magia", "Capoeira tem axé"],
    note: "Le chant relie la capoeira à ses lieux et à son axé."
  },
  {
    id: "song_simao",
    title: "Sim, sim, sim / Não, não, não",
    focus: "Réponse claire du chœur",
    lines: ["Sim, sim, sim", "Não, não, não", "Hoje tem capoeira"],
    note: "Parfait pour réviser les réponses courtes en portugais."
  }
];

const LIBRARY = [
  { id: "lib_capoeira", skill: "culture", title: "Capoeira", text: "Art afro-brésilien mêlant jeu, lutte, musique, chant, culture et mouvement." },
  { id: "lib_roda", skill: "culture", title: "Roda", text: "Cercle dans lequel les capoeiristes jouent, chantent, frappent les mains et suivent la bateria." },
  { id: "lib_axe", skill: "portugais", title: "Axé", text: "Énergie positive et force collective qui circule dans la roda." },
  { id: "lib_dobrao", skill: "berimbau", title: "Dobrão", text: "Pièce ou pierre tenue contre l'arame du berimbau pour produire les sons ouvert, fermé ou bourdonné." },
  { id: "lib_berimbau", skill: "berimbau", title: "Berimbau", text: "Instrument principal de la capoeira. Il guide le jeu et l'énergie de la roda." },
  { id: "lib_mandinga", skill: "culture", title: "Mandinga", text: "Malice, ruse et subtilité dans le jeu, le chant et l'attitude en roda." },
  { id: "lib_paranaue", skill: "chants", title: "Paranauê", text: "Chant très connu de capoeira, souvent appris très tôt par les pratiquants." },
  { id: "lib_marinheiro", skill: "chants", title: "Marinheiro Só", text: "Chant utile pour mémoriser des mots comme quem, ensinou et nadar." },
  { id: "lib_louvacao", skill: "chants", title: "Louvação", text: "Partie chantée qui salue, honore et installe l'énergie avant ou pendant la roda." },
  { id: "lib_song_refrain", skill: "chants", title: "Refrain", text: "Phrase courte reprise par le chœur. C'est souvent la meilleure porte d'entrée pour chanter." },
  { id: "lib_queixada", skill: "techniques", title: "Queixada", text: "Coup de pied circulaire très fréquent dans les bases de la capoeira." }
];

const QUESTIONS = [
  { id:"culture_001", node:"node_5", skill:"culture", type:"mcq", unlock:"lib_capoeira", question:"Dans quel pays la capoeira est-elle née ?", answer:"Brésil", choices:["Angola","Portugal","Mozambique","Brésil"], explanation:"La capoeira est née au Brésil." },
  { id:"culture_002", node:"node_5", skill:"culture", type:"mcq", question:"La capoeira a été développée principalement par :", answer:"Des esclaves africains", choices:["Des soldats","Des marins","Des esclaves africains","Des prêtres"], explanation:"La capoeira a été développée principalement par des esclaves africains et leurs descendants au Brésil." },
  { id:"culture_003", node:"node_5", skill:"culture", type:"mcq", unlock:"lib_roda", question:"Qu'est-ce qu'une roda ?", answer:"Le cercle où se déroule le jeu", choices:["Une chanson","Un instrument","Le cercle où se déroule le jeu","Une compétition"], explanation:"La roda est le cercle où se déroule le jeu de capoeira." },
  { id:"culture_004", node:"node_5", skill:"culture", type:"mcq", unlock:"lib_berimbau", question:"Quel est l'instrument le plus important dans une roda ?", answer:"Berimbau", choices:["Pandeiro","Atabaque","Agogo","Berimbau"], explanation:"Le berimbau guide traditionnellement la roda." },
  { id:"culture_005", node:"node_5", skill:"culture", type:"mcq", question:"Comment appelle-t-on un pratiquant de capoeira ?", answer:"Capoeiriste", choices:["Capoeirien","Rodador","Capoeiriste","Gingador"], explanation:"Un pratiquant de capoeira est un capoeiriste." },
  { id:"culture_006", node:"node_5", skill:"culture", type:"mcq", unlock:"lib_axe", question:"Que signifie « axé » ?", answer:"Une énergie positive", choices:["Une attaque","Une esquive","Un chant","Une énergie positive"], explanation:"Axé désigne une énergie positive dans la roda." },
  { id:"culture_007", node:"node_5", skill:"culture", type:"mcq", question:"Avant de jouer, les capoeiristes entrent généralement :", answer:"Au pied du berimbau", choices:["Par le centre","Derrière les musiciens","Au pied du berimbau","En courant"], explanation:"On entre généralement au pied du berimbau." },
  { id:"culture_008", node:"node_5", skill:"culture", type:"mcq", question:"La capoeira est :", answer:"Un mélange des trois", choices:["Seulement une danse","Seulement un combat","Seulement une musique","Un mélange des trois"], explanation:"La capoeira mélange danse, combat et musique." },
  { id:"culture_009", node:"node_5", skill:"culture", type:"mcq", question:"Comment appelle-t-on le maître de capoeira ?", answer:"Mestre", choices:["Professor","Instrutor","Mestre","Monitor"], explanation:"Le maître de capoeira s'appelle mestre." },
  { id:"culture_010", node:"node_5", skill:"culture", type:"mcq", question:"Pourquoi chante-t-on dans une roda ?", answer:"Pour accompagner et influencer le jeu", choices:["Pour remplir le silence","Pour faire joli","Pour accompagner et influencer le jeu","Pour impressionner le public"], explanation:"Le chant accompagne et influence l'énergie du jeu." },

  { id:"culture_011", node:"node_5", skill:"culture", type:"mcq", question:"Qu'est-ce qu'un apelido ?", answer:"Un surnom", choices:["Une attaque","Un instrument","Un surnom","Une chanson"], explanation:"Un apelido est un surnom." },
  { id:"culture_012", node:"node_5", skill:"culture", type:"mcq", question:"Pourquoi les capoeiristes reçoivent-ils souvent un apelido ?", answer:"Par tradition et esprit de groupe", choices:["Pour remplacer leur prénom","Pour obtenir une corde","Par tradition et esprit de groupe","Pour devenir professeur"], explanation:"L'apelido fait partie de la tradition et de l'esprit de groupe." },
  { id:"culture_013", node:"node_5", skill:"culture", type:"mcq", question:"Que signifie « malícia » ?", answer:"La ruse dans le jeu", choices:["La force physique","La vitesse","La ruse dans le jeu","La souplesse"], explanation:"La malícia est la ruse dans le jeu." },
  { id:"culture_014", node:"node_5", skill:"culture", type:"mcq", question:"Pourquoi la malícia est-elle importante ?", answer:"Pour anticiper et tromper son partenaire", choices:["Pour frapper plus fort","Pour gagner des compétitions","Pour anticiper et tromper son partenaire","Pour chanter mieux"], explanation:"La malícia aide à anticiper et à tromper son partenaire." },
  { id:"culture_015", node:"node_5", skill:"culture", type:"mcq", unlock:"lib_mandinga", question:"Que signifie « mandinga » ?", answer:"Une forme de ruse et de jeu psychologique", choices:["Une attaque secrète","Une chanson","Une forme de ruse et de jeu psychologique","Un rythme"], explanation:"La mandinga évoque la ruse, la malice et le jeu psychologique." },
  { id:"culture_016", node:"node_5", skill:"culture", type:"mcq", question:"Comment appelle-t-on l'ensemble des musiciens ?", answer:"Bateria", choices:["Banda","Grupo","Orquestra","Bateria"], explanation:"L'ensemble des musiciens s'appelle la bateria." },
  { id:"culture_017", node:"node_5", skill:"culture", type:"mcq", unlock:"lib_louvacao", question:"Qu'est-ce qu'une ladainha ?", answer:"Un chant d'ouverture", choices:["Un coup de pied","Une esquive","Un chant d'ouverture","Un rythme"], explanation:"La ladainha est un chant d'ouverture." },
  { id:"culture_018", node:"node_5", skill:"culture", type:"mcq", question:"Qu'est-ce qu'un corrido ?", answer:"Un chant en appel-réponse", choices:["Une attaque","Une salutation","Un chant en appel-réponse","Une esquive"], explanation:"Le corrido est un chant en appel-réponse." },
  { id:"culture_019", node:"node_5", skill:"culture", type:"mcq", question:"Qu'est-ce qu'une chula ?", answer:"Un chant de transition", choices:["Un rythme","Une esquive","Un chant de transition","Une cérémonie"], explanation:"La chula est un chant de transition." },
  { id:"culture_020", node:"node_5", skill:"culture", type:"mcq", question:"Pourquoi la musique influence-t-elle le jeu ?", answer:"Parce qu'elle guide l'énergie et le style du jeu", choices:["Parce qu'elle donne des points","Parce qu'elle est obligatoire","Parce qu'elle guide l'énergie et le style du jeu","Parce qu'elle remplace l'arbitre"], explanation:"La musique guide l'énergie et le style du jeu." },

  { id:"culture_021", node:"node_5", skill:"culture", type:"mcq", question:"Pendant longtemps, la capoeira était :", answer:"Interdite au Brésil", choices:["Encouragée par le gouvernement","Enseignée à l'école","Interdite au Brésil","Réservée aux militaires"], explanation:"Pendant longtemps, la capoeira a été interdite au Brésil." },
  { id:"culture_022", node:"node_5", skill:"culture", type:"mcq", question:"Pourquoi la capoeira a-t-elle été interdite ?", answer:"Associée à la criminalité et à la rébellion", choices:["Trop dangereuse pour les enfants","Trop difficile à apprendre","Associée à la criminalité et à la rébellion","Manque d'enseignants"], explanation:"Elle a été associée à la criminalité et à la rébellion." },
  { id:"culture_023", node:"node_5", skill:"culture", type:"mcq", question:"Qui est considéré comme le créateur de la Capoeira Regional ?", answer:"Mestre Bimba", choices:["Mestre Pastinha","Mestre João Grande","Mestre Bimba","Mestre Camisa"], explanation:"Mestre Bimba est considéré comme le créateur de la Capoeira Regional." },
  { id:"culture_024", node:"node_5", skill:"culture", type:"mcq", question:"Qui est la figure emblématique de la Capoeira Angola ?", answer:"Mestre Pastinha", choices:["Mestre Bimba","Mestre Suassuna","Mestre Pastinha","Mestre Acordeon"], explanation:"Mestre Pastinha est une figure emblématique de la Capoeira Angola." },
  { id:"culture_025", node:"node_5", skill:"culture", type:"mcq", question:"La Capoeira Regional a été créée pour :", answer:"Structurer et valoriser la capoeira", choices:["Supprimer la musique","Jouer plus lentement","Structurer et valoriser la capoeira","Remplacer la roda"], explanation:"La Capoeira Regional a contribué à structurer et valoriser la capoeira." },
  { id:"culture_026", node:"node_5", skill:"culture", type:"mcq", question:"La Capoeira Angola est souvent associée à :", answer:"Un jeu plus traditionnel", choices:["Un jeu sportif","Un jeu rapide","Un jeu plus traditionnel","Une compétition"], explanation:"La Capoeira Angola est souvent associée à un jeu plus traditionnel." },
  { id:"culture_027", node:"node_5", skill:"culture", type:"mcq", question:"Quel élément est au cœur de la transmission de la capoeira ?", answer:"L'oralité", choices:["Les livres","Les vidéos","Les examens","L'oralité"], explanation:"L'oralité est au cœur de la transmission de la capoeira." },
  { id:"culture_028", node:"node_5", skill:"culture", type:"mcq", question:"En 2014, la capoeira a été inscrite :", answer:"Au patrimoine culturel immatériel de l'UNESCO", choices:["Aux Jeux Olympiques","Comme sport national","Au patrimoine culturel immatériel de l'UNESCO","Au patrimoine portugais"], explanation:"En 2014, la roda de capoeira a été inscrite au patrimoine culturel immatériel de l'UNESCO." },
  { id:"culture_029", node:"node_5", skill:"culture", type:"mcq", question:"Que représente idéalement un partenaire dans la roda ?", answer:"Une personne avec qui construire le jeu", choices:["Un ennemi","Un adversaire à vaincre","Un juge","Une personne avec qui construire le jeu"], explanation:"Dans l'idéal, le partenaire est une personne avec qui construire le jeu." },
  { id:"culture_030", node:"node_5", skill:"culture", type:"mcq", question:"Quelle phrase décrit le mieux la capoeira ?", answer:"Un art mêlant combat, musique, culture et expression", choices:["Un sport de combat","Une danse folklorique","Une musique traditionnelle","Un art mêlant combat, musique, culture et expression"], explanation:"La capoeira est un art mêlant combat, musique, culture et expression." },

  { id:"port_001", node:"node_6", skill:"portugais", type:"mcq", question:"Que signifie « Olá » ?", answer:"Bonjour", choices:["Merci","Au revoir","Bonjour","Bonne nuit"], explanation:"Olá signifie bonjour." },
  { id:"port_002", node:"node_6", skill:"portugais", type:"mcq", question:"Que signifie « Bom dia » ?", answer:"Bonjour", choices:["Bonsoir","Merci","Bonjour","À demain"], explanation:"Bom dia signifie bonjour." },
  { id:"port_003", node:"node_6", skill:"portugais", type:"mcq", question:"Que signifie « Boa tarde » ?", answer:"Bon après-midi", choices:["Bonjour","Bonne nuit","Au revoir","Bon après-midi"], explanation:"Boa tarde signifie bon après-midi." },
  { id:"port_004", node:"node_6", skill:"portugais", type:"mcq", question:"Que signifie « Boa noite » ?", answer:"Bonsoir", choices:["Bonjour","Merci","Bonsoir","À bientôt"], explanation:"Boa noite signifie bonsoir ou bonne nuit selon le contexte." },
  { id:"port_005", node:"node_6", skill:"portugais", type:"mcq", question:"Que signifie « Obrigado » ?", answer:"Merci", choices:["Bonjour","S'il vous plaît","Merci","Excuse-moi"], explanation:"Obrigado signifie merci." },
  { id:"port_006", node:"node_6", skill:"portugais", type:"mcq", question:"Que signifie « Por favor » ?", answer:"S'il te plaît", choices:["Merci","Bonjour","S'il te plaît","Au revoir"], explanation:"Por favor signifie s'il te plaît." },
  { id:"port_007", node:"node_6", skill:"portugais", type:"mcq", question:"Que signifie « Tudo bem ? » ?", answer:"Ça va ?", choices:["Qui es-tu ?","Où vas-tu ?","Ça va ?","Tu joues ?"], explanation:"Tudo bem ? signifie ça va ?" },
  { id:"port_008", node:"node_6", skill:"portugais", type:"mcq", question:"Comment répondre à « Tudo bem ? »", answer:"Tudo bem", choices:["Adeus","Vamos jogar","Obrigado","Tudo bem"], explanation:"On peut répondre Tudo bem." },
  { id:"port_009", node:"node_6", skill:"portugais", type:"mcq", question:"« Pé » signifie :", answer:"Pied", choices:["Main","Jambe","Pied","Tête"], explanation:"Pé signifie pied." },
  { id:"port_010", node:"node_6", skill:"portugais", type:"mcq", question:"« Mão » signifie :", answer:"Main", choices:["Pied","Bras","Tête","Main"], explanation:"Mão signifie main." },
  { id:"port_011", node:"node_6", skill:"portugais", type:"mcq", question:"« Cabeça » signifie :", answer:"Tête", choices:["Bras","Pied","Tête","Corps"], explanation:"Cabeça signifie tête." },
  { id:"port_012", node:"node_6", skill:"portugais", type:"mcq", question:"« Braço » signifie :", answer:"Bras", choices:["Jambe","Main","Bras","Dos"], explanation:"Braço signifie bras." },
  { id:"port_013", node:"node_6", skill:"portugais", type:"mcq", question:"« Perna » signifie :", answer:"Jambe", choices:["Bras","Main","Jambe","Cou"], explanation:"Perna signifie jambe." },
  { id:"port_014", node:"node_6", skill:"portugais", type:"mcq", question:"« Corpo » signifie :", answer:"Corps", choices:["Tête","Jambe","Bras","Corps"], explanation:"Corpo signifie corps." },
  { id:"port_015", node:"node_6", skill:"portugais", type:"mcq", question:"« Olho » signifie :", answer:"Œil", choices:["Nez","Main","Œil","Oreille"], explanation:"Olho signifie œil." },
  { id:"port_016", node:"node_6", skill:"portugais", type:"mcq", question:"« Nariz » signifie :", answer:"Nez", choices:["Bouche","Oreille","Nez","Œil"], explanation:"Nariz signifie nez." },
  { id:"port_017", node:"node_6", skill:"portugais", type:"mcq", question:"« Direita » signifie :", answer:"Droite", choices:["Derrière","Gauche","Droite","Devant"], explanation:"Direita signifie droite." },
  { id:"port_018", node:"node_6", skill:"portugais", type:"mcq", question:"« Esquerda » signifie :", answer:"Gauche", choices:["Derrière","Devant","Gauche","Droite"], explanation:"Esquerda signifie gauche." },
  { id:"port_019", node:"node_6", skill:"portugais", type:"mcq", question:"« Frente » signifie :", answer:"Devant", choices:["Gauche","Derrière","Devant","Droite"], explanation:"Frente signifie devant." },
  { id:"port_020", node:"node_6", skill:"portugais", type:"mcq", question:"« Atrás » signifie :", answer:"Derrière", choices:["Devant","Droite","Gauche","Derrière"], explanation:"Atrás signifie derrière." },
  { id:"port_021", node:"node_6", skill:"portugais", type:"mcq", question:"« Ginga ! » signifie :", answer:"Fais la ginga !", choices:["Chante !","Saute !","Fais la ginga !","Arrête !"], explanation:"Ginga ! veut dire fais la ginga." },
  { id:"port_022", node:"node_6", skill:"portugais", type:"mcq", question:"« Mais baixo ! » signifie :", answer:"Plus bas", choices:["Plus haut","Plus vite","Plus bas","Plus fort"], explanation:"Mais baixo signifie plus bas." },
  { id:"port_023", node:"node_6", skill:"portugais", type:"mcq", question:"« Mais rápido ! » signifie :", answer:"Plus vite", choices:["Plus lentement","Plus bas","Plus doucement","Plus vite"], explanation:"Mais rápido signifie plus vite." },
  { id:"port_024", node:"node_6", skill:"portugais", type:"mcq", question:"« Devagar ! » signifie :", answer:"Doucement", choices:["Plus vite","Plus haut","Doucement","Tourne"], explanation:"Devagar signifie doucement." },
  { id:"port_025", node:"node_6", skill:"portugais", type:"mcq", question:"« Continua ! » signifie :", answer:"Continue", choices:["Arrête","Écoute","Chante","Continue"], explanation:"Continua signifie continue." },
  { id:"port_026", node:"node_6", skill:"portugais", type:"mcq", question:"« Olha ! » signifie :", answer:"Regarde", choices:["Chante","Saute","Regarde","Tourne"], explanation:"Olha signifie regarde." },
  { id:"port_027", node:"node_6", skill:"portugais", type:"mcq", question:"« Escuta ! » signifie :", answer:"Écoute", choices:["Regarde","Tourne","Saute","Écoute"], explanation:"Escuta signifie écoute." },
  { id:"port_028", node:"node_6", skill:"portugais", type:"mcq", question:"« Volta ! » signifie :", answer:"Reviens / tourne", choices:["Saute","Chante","Reviens / tourne","Esquive"], explanation:"Volta peut vouloir dire reviens ou tourne selon le contexte." },
  { id:"port_029", node:"node_6", skill:"portugais", type:"mcq", question:"« Vamos jogar » signifie :", answer:"Allons jouer", choices:["Allons chanter","Allons manger","Allons jouer","Allons partir"], explanation:"Vamos jogar signifie allons jouer." },
  { id:"port_030", node:"node_6", skill:"portugais", type:"mcq", question:"« Jogo » signifie :", answer:"Jeu", choices:["Chant","Instrument","Jeu","Danse"], explanation:"Jogo signifie jeu." },
  { id:"port_031", node:"node_6", skill:"portugais", type:"mcq", unlock:"lib_roda", question:"« Roda » signifie :", answer:"Cercle de jeu", choices:["Instrument","Chant","Esquive","Cercle de jeu"], explanation:"Roda signifie cercle de jeu." },
  { id:"port_032", node:"node_6", skill:"portugais", type:"mcq", unlock:"lib_axe", question:"« Axé » signifie :", answer:"Énergie positive", choices:["Coup de pied","Chant","Énergie positive","Instrument"], explanation:"Axé signifie énergie positive." },
  { id:"port_033", node:"node_6", skill:"portugais", type:"mcq", question:"« Mestre » signifie :", answer:"Maître", choices:["Élève","Musicien","Chanteur","Maître"], explanation:"Mestre signifie maître." },
  { id:"port_034", node:"node_6", skill:"portugais", type:"mcq", question:"« Aluno » signifie :", answer:"Élève", choices:["Professeur","Musicien","Élève","Spectateur"], explanation:"Aluno signifie élève." },
  { id:"port_035", node:"node_6", skill:"portugais", type:"mcq", question:"« Apelido » signifie :", answer:"Surnom", choices:["Chant","Instrument","Surnom","Coup de pied"], explanation:"Apelido signifie surnom." },
  { id:"port_036", node:"node_6", skill:"portugais", type:"mcq", question:"« Jogar » signifie :", answer:"Jouer", choices:["Chanter","Courir","Jouer","Danser"], explanation:"Jogar signifie jouer." },
  { id:"port_037", node:"node_6", skill:"portugais", type:"mcq", question:"« Cantar » signifie :", answer:"Chanter", choices:["Jouer","Courir","Danser","Chanter"], explanation:"Cantar signifie chanter." },
  { id:"port_038", node:"node_6", skill:"portugais", type:"mcq", question:"« Treinar » signifie :", answer:"S'entraîner", choices:["Jouer","Chanter","S'entraîner","Regarder"], explanation:"Treinar signifie s'entraîner." },
  { id:"port_039", node:"node_6", skill:"portugais", type:"mcq", question:"« Aprender » signifie :", answer:"Apprendre", choices:["Enseigner","Regarder","Apprendre","Courir"], explanation:"Aprender signifie apprendre." },
  { id:"port_040", node:"node_6", skill:"portugais", type:"mcq", question:"« Ensinar » signifie :", answer:"Enseigner", choices:["Jouer","Apprendre","Chanter","Enseigner"], explanation:"Ensinar signifie enseigner." },
  { id:"port_041", node:"node_6", skill:"portugais", type:"mcq", question:"« Malícia » signifie :", answer:"Ruse", choices:["Force","Souplesse","Ruse","Rapidité"], explanation:"Malícia signifie ruse." },
  { id:"port_042", node:"node_6", skill:"portugais", type:"mcq", unlock:"lib_mandinga", question:"« Mandinga » signifie :", answer:"Astuce / magie du jeu", choices:["Instrument","Coup de pied","Astuce / magie du jeu","Chanson"], explanation:"Mandinga signifie astuce ou magie du jeu." },
  { id:"port_043", node:"node_6", skill:"portugais", type:"mcq", question:"« Companheiro » signifie :", answer:"Partenaire", choices:["Ennemi","Arbitre","Partenaire","Musicien"], explanation:"Companheiro signifie partenaire." },
  { id:"port_044", node:"node_6", skill:"portugais", type:"mcq", question:"« Camarada » signifie :", answer:"Camarade", choices:["Maître","Professeur","Camarade","Élève"], explanation:"Camarada signifie camarade." },
  { id:"port_045", node:"node_6", skill:"portugais", type:"mcq", unlock:"lib_berimbau", question:"« Berimbau » signifie :", answer:"Arc musical", choices:["Tambour","Hochet","Arc musical","Cloche"], explanation:"Le berimbau est un arc musical." },
  { id:"port_046", node:"node_6", skill:"portugais", type:"mcq", question:"« Pandeiro » signifie :", answer:"Tambourin", choices:["Tambour","Arc musical","Tambourin","Cloche"], explanation:"Pandeiro signifie tambourin." },
  { id:"port_047", node:"node_6", skill:"portugais", type:"mcq", question:"« Atabaque » signifie :", answer:"Grand tambour", choices:["Tambourin","Arc musical","Grand tambour","Hochet"], explanation:"L'atabaque est un grand tambour." },
  { id:"port_048", node:"node_6", skill:"portugais", type:"mcq", question:"« Toque » signifie :", answer:"Rythme", choices:["Chant","Jeu","Mouvement","Rythme"], explanation:"Toque signifie rythme." },
  { id:"port_049", node:"node_6", skill:"portugais", type:"mcq", unlock:"lib_louvacao", question:"« Ladainha » signifie :", answer:"Chant d'ouverture", choices:["Esquive","Instrument","Chant d'ouverture","Projection"], explanation:"Ladainha signifie chant d'ouverture." },
  { id:"port_050", node:"node_6", skill:"portugais", type:"mcq", question:"« Corrido » signifie :", answer:"Chant en appel-réponse", choices:["Projection","Instrument","Esquive","Chant en appel-réponse"], explanation:"Corrido signifie chant en appel-réponse." },

  { id:"instr_001", node:"node_7", skill:"berimbau", type:"mcq", unlock:"lib_berimbau", question:"Quel instrument dirige traditionnellement la roda ?", answer:"Berimbau", choices:["Atabaque","Pandeiro","Agogo","Berimbau"], explanation:"Le berimbau dirige traditionnellement la roda." },
  { id:"instr_002", node:"node_7", skill:"berimbau", type:"mcq", question:"Le berimbau possède :", answer:"Une seule corde", choices:["Deux cordes","Trois cordes","Une seule corde","Quatre cordes"], explanation:"Le berimbau possède une seule corde." },
  { id:"instr_003", node:"node_7", skill:"berimbau", type:"mcq", question:"La caisse de résonance du berimbau est :", answer:"Une calebasse", choices:["En bois","En métal","Une calebasse","En cuir"], explanation:"La calebasse sert de caisse de résonance." },
  { id:"instr_004", node:"node_7", skill:"berimbau", type:"mcq", question:"Comment appelle-t-on la calebasse du berimbau ?", answer:"Cabaça", choices:["Caxixi","Baqueta","Dobrão","Cabaça"], explanation:"La calebasse du berimbau s'appelle la cabaça." },
  { id:"instr_005", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel instrument est un hochet ?", answer:"Caxixi", choices:["Agogo","Atabaque","Caxixi","Pandeiro"], explanation:"Le caxixi est un hochet." },
  { id:"instr_006", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel instrument est un tambour ?", answer:"Atabaque", choices:["Berimbau","Caxixi","Atabaque","Agogo"], explanation:"L'atabaque est un tambour." },
  { id:"instr_007", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel instrument ressemble à un tambourin ?", answer:"Pandeiro", choices:["Agogo","Berimbau","Pandeiro","Atabaque"], explanation:"Le pandeiro ressemble à un tambourin." },
  { id:"instr_008", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel instrument est constitué de cloches métalliques ?", answer:"Agogo", choices:["Pandeiro","Caxixi","Berimbau","Agogo"], explanation:"L'agogo est constitué de cloches métalliques." },
  { id:"instr_009", node:"node_7", skill:"berimbau", type:"mcq", question:"Que tient-on généralement avec le berimbau ?", answer:"Caxixi", choices:["Pandeiro","Agogo","Caxixi","Atabaque"], explanation:"On tient souvent le caxixi avec le berimbau." },
  { id:"instr_010", node:"node_7", skill:"berimbau", type:"mcq", question:"Avec quoi frappe-t-on la corde du berimbau ?", answer:"Baqueta", choices:["Main nue","Pierre","Baqueta","Baguette de tambour"], explanation:"On frappe la corde avec la baqueta." },

  { id:"instr_011", node:"node_7", skill:"berimbau", type:"mcq", unlock:"lib_dobrao", question:"Le dobrão sert à :", answer:"Modifier le son", choices:["Accorder le berimbau","Frapper le berimbau","Modifier le son","Jouer du rythme"], explanation:"Le dobrão modifie le son du berimbau." },
  { id:"instr_012", node:"node_7", skill:"berimbau", type:"mcq", question:"Le caxixi est rempli :", answer:"De graines", choices:["De sable","De métal","De graines","D'eau"], explanation:"Le caxixi est généralement rempli de graines." },
  { id:"instr_013", node:"node_7", skill:"berimbau", type:"mcq", question:"L'atabaque est joué :", answer:"Avec les mains", choices:["Avec une baguette","Avec le pied","Avec les mains","Avec une pierre"], explanation:"L'atabaque est joué avec les mains." },
  { id:"instr_014", node:"node_7", skill:"berimbau", type:"mcq", question:"Combien trouve-t-on souvent de berimbaus dans une bateria complète ?", answer:"3", choices:["1","2","3","5"], explanation:"On trouve souvent trois berimbaus dans une bateria complète." },
  { id:"instr_015", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel berimbau possède généralement le son le plus grave ?", answer:"Gunga", choices:["Viola","Médio","Gunga","Agogo"], explanation:"Le gunga est généralement le plus grave." },
  { id:"instr_016", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel berimbau possède généralement le son intermédiaire ?", answer:"Médio", choices:["Gunga","Médio","Viola","Atabaque"], explanation:"Le médio possède généralement le son intermédiaire." },
  { id:"instr_017", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel berimbau possède souvent le son le plus aigu ?", answer:"Viola", choices:["Gunga","Médio","Viola","Agogo"], explanation:"La viola possède souvent le son le plus aigu." },
  { id:"instr_018", node:"node_7", skill:"berimbau", type:"mcq", question:"Le gunga est généralement :", answer:"Le plus grave", choices:["Le plus petit","Le plus léger","Le plus grave","Le plus rapide"], explanation:"Le gunga est généralement le plus grave." },
  { id:"instr_019", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel instrument marque fortement le rythme principal ?", answer:"Atabaque", choices:["Caxixi","Agogo","Atabaque","Viola"], explanation:"L'atabaque marque fortement le rythme principal." },
  { id:"instr_020", node:"node_7", skill:"berimbau", type:"mcq", question:"Comment appelle-t-on l'ensemble musical ?", answer:"Bateria", choices:["Orquestra","Banda","Bateria","Grupo"], explanation:"L'ensemble musical s'appelle la bateria." },

  { id:"instr_021", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel instrument donne souvent les variations rythmiques ?", answer:"Viola", choices:["Gunga","Médio","Viola","Atabaque"], explanation:"La viola donne souvent des variations rythmiques." },
  { id:"instr_022", node:"node_7", skill:"berimbau", type:"mcq", question:"Le médio sert souvent à :", answer:"Soutenir le rythme", choices:["Improviser","Soutenir le rythme","Chanter","Accorder"], explanation:"Le médio sert souvent à soutenir le rythme." },
  { id:"instr_023", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel élément du berimbau produit les sons ouverts et fermés ?", answer:"Dobrão", choices:["Baqueta","Caxixi","Dobrão","Corde"], explanation:"Le dobrão permet de produire les sons ouverts et fermés." },
  { id:"instr_024", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel instrument est indispensable dans presque toutes les rodas ?", answer:"Berimbau", choices:["Agogo","Pandeiro","Berimbau","Reco-reco"], explanation:"Le berimbau est indispensable dans presque toutes les rodas." },
  { id:"instr_025", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel instrument n'est PAS un tambour ?", answer:"Berimbau", choices:["Atabaque","Pandeiro","Berimbau","Aucun"], explanation:"Le berimbau n'est pas un tambour, c'est un arc musical." },
  { id:"instr_026", node:"node_7", skill:"berimbau", type:"mcq", question:"Le caxixi ajoute principalement :", answer:"Texture sonore", choices:["Mélodie","Harmonie","Texture sonore","Graves"], explanation:"Le caxixi ajoute principalement une texture sonore." },
  { id:"instr_027", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel instrument produit le « ding » du berimbau ?", answer:"La corde frappée", choices:["Caxixi","Atabaque","La corde frappée","Agogo"], explanation:"Le son vient de la corde frappée du berimbau." },
  { id:"instr_028", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel instrument peut jouer seul pour démarrer une roda ?", answer:"Berimbau", choices:["Atabaque","Pandeiro","Berimbau","Agogo"], explanation:"Le berimbau peut jouer seul pour démarrer une roda." },
  { id:"instr_029", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel instrument accompagne souvent les chants ?", answer:"Pandeiro", choices:["Tous","Aucun","Pandeiro","Seulement le gunga"], explanation:"Le pandeiro accompagne souvent les chants." },
  { id:"instr_030", node:"node_7", skill:"berimbau", type:"mcq", question:"Quel instrument est considéré comme le cœur musical de la capoeira ?", answer:"Berimbau", choices:["Atabaque","Pandeiro","Caxixi","Berimbau"], explanation:"Le berimbau est considéré comme le cœur musical de la capoeira." },

  { id:"q031", node:"song_bank", skill:"berimbau", type:"mcq", question:"Pour un son ouvert, le dobrão est…", answer:"Éloigné de l’arame", choices:["Éloigné de l’arame","Appuyé fortement","Posé légèrement","Remplacé par la cabaça"], explanation:"Sans contact du dobrão sur l’arame, le son est ouvert." },
  { id:"q032", node:"song_bank", skill:"berimbau", type:"mcq", question:"Le son ouvert peut être représenté par…", answer:"DONG", choices:["DONG","TCHIN","BZZZ","CLAC"], explanation:"DONG représente souvent le son ouvert." },
  { id:"q033", node:"song_bank", skill:"berimbau", type:"mcq", question:"Pour un son fermé, le dobrão est…", answer:"Appuyé contre l’arame", choices:["Appuyé contre l’arame","Loin de l’arame","Sur la cabaça","Dans le caxixi"], explanation:"Le dobrão appuyé ferme le son." },
  { id:"q034", node:"song_bank", skill:"berimbau", type:"mcq", question:"Le son fermé peut être représenté par…", answer:"TCHIN", choices:["TCHIN","DONG","BZZZ","PAF"], explanation:"TCHIN représente le son fermé." },
  { id:"q035", node:"song_bank", skill:"berimbau", type:"mcq", question:"Pour un son bourdonné, le dobrão est…", answer:"En contact léger avec l’arame", choices:["En contact léger avec l’arame","Très loin de l’arame","Remplacé par la baqueta","Posé sur la cabaça"], explanation:"Le contact léger produit un son bourdonnant." },
  { id:"q036", node:"song_bank", skill:"berimbau", type:"mcq", question:"Le son bourdonné peut être représenté par…", answer:"BZZZ", choices:["BZZZ","DONG","TCHIN","TOC"], explanation:"BZZZ représente le son bourdonné." },
  { id:"q037", node:"song_bank", skill:"berimbau", type:"mcq", question:"Dans « DONG — TCHIN — BZZZ », DONG correspond à…", answer:"Ouvert", choices:["Ouvert","Fermé","Bourdonné","Silence"], explanation:"DONG = ouvert." },
  { id:"q038", node:"song_bank", skill:"berimbau", type:"mcq", question:"Dans « DONG — TCHIN — BZZZ », TCHIN correspond à…", answer:"Fermé", choices:["Fermé","Ouvert","Bourdonné","Caxixi"], explanation:"TCHIN = fermé." },
  { id:"q039", node:"song_bank", skill:"berimbau", type:"mcq", question:"Dans « DONG — TCHIN — BZZZ », BZZZ correspond à…", answer:"Bourdonné", choices:["Bourdonné","Ouvert","Fermé","Cabaça"], explanation:"BZZZ = son bourdonné." },
  { id:"q040", node:"song_bank", skill:"berimbau", type:"order", question:"Remets les sons dans l’ordre : ouvert, fermé, bourdonné.", lines:["DONG","TCHIN","BZZZ"], correct:["DONG","TCHIN","BZZZ"], explanation:"Ouvert = DONG, fermé = TCHIN, bourdonné = BZZZ." },

  { id:"q041", node:"song_bank", skill:"chants", type:"mcq", question:"Dans beaucoup de chants de capoeira, on retrouve…", answer:"Un système appel-réponse", choices:["Un système appel-réponse","Un silence complet","Un solo sans chœur","Uniquement des cris"], explanation:"Le meneur chante, le chœur répond." },
  { id:"q042", node:"song_bank", skill:"chants", type:"hole", unlock:"lib_paranaue", question:"Complète le refrain.", text:"Paranauê, Paranauê,\n{Paraná}", holes:[{answer:"Paraná", choices:["Paraná","camará","mandinga","Angola"]}], explanation:"Le refrain classique est « Paranauê, Paranauê, Paraná »." },
  { id:"q043", node:"song_bank", skill:"chants", type:"hole", question:"Complète la réponse.", text:"Iê viva meu mestre,\n{camará}", holes:[{answer:"camará", choices:["camará","Paraná","ginga","cabaça"]}], explanation:"La réponse finit souvent par camará." },
  { id:"q044", node:"song_bank", skill:"chants", type:"mcq", question:"Un corrido est plutôt…", answer:"Un chant court répété pendant le jeu", choices:["Un chant court répété pendant le jeu","Une esquive","Un instrument","Une corde"], explanation:"Les corridos accompagnent souvent le jeu." },
  { id:"q045", node:"song_bank", skill:"chants", type:"mcq", question:"La louvação sert souvent à…", answer:"Saluer, honorer ou appeler une réponse", choices:["Saluer, honorer ou appeler une réponse","Frapper la corde","Faire une acrobatie","Arrêter la roda"], explanation:"La louvação fonctionne beaucoup en appel-réponse." },
  { id:"q046", node:"song_bank", skill:"chants", type:"hole", question:"Complète cette phrase de chant.", text:"Iê viva meu {mestre},\nIê viva meu mestre, camará", holes:[{answer:"mestre", choices:["mestre","aluno","dobrao","caxixi"]}], explanation:"On honore le mestre dans ce type de chant." },
  { id:"q047", node:"song_bank", skill:"chants", type:"order", question:"Remets ces lignes dans l’ordre.", lines:["Iê viva meu mestre","Iê viva meu mestre, camará","Iê quem me ensinou","Iê quem me ensinou, camará"], correct:["Iê viva meu mestre","Iê viva meu mestre, camará","Iê quem me ensinou","Iê quem me ensinou, camará"], explanation:"On alterne appel et réponse." },
  { id:"q048", node:"song_bank", skill:"chants", type:"mcq", question:"Quand le chœur répond, il doit surtout…", answer:"Soutenir le meneur et garder l’énergie", choices:["Soutenir le meneur et garder l’énergie","Changer de chant au hasard","Couper le berimbau","Parler plus fort que tout le monde"], explanation:"Le chœur soutient l’axé." },
  { id:"q049", node:"song_bank", skill:"chants", type:"hole", question:"Complète la phrase.", text:"Paranauê, Paranauê,\nParanauê, {Paraná}", holes:[{answer:"Paraná", choices:["Paraná","caxixi","mestre","jogo"]}], explanation:"La répétition du refrain construit la mémoire." },
  { id:"q050", node:"song_bank", skill:"chants", type:"mcq", question:"Apprendre les paroles aide à…", answer:"Participer activement à la roda", choices:["Participer activement à la roda","Éviter de s’entraîner","Remplacer le berimbau","Changer le toque"], explanation:"Connaître les chants aide à entrer dans la culture de la roda." },

  { id:"tech_001", node:"node_8", skill:"techniques", type:"mcq", question:"Quel est le mouvement de base de la capoeira ?", answer:"Ginga", choices:["Armada","Queixada","Negativa","Ginga"], explanation:"La ginga est le mouvement de base de la capoeira." },
  { id:"tech_002", node:"node_8", skill:"techniques", type:"mcq", question:"À quoi sert principalement la ginga ?", answer:"Se déplacer et rester mobile", choices:["Chanter","Attaquer","Se déplacer et rester mobile","Saluer"], explanation:"La ginga sert à se déplacer et à rester mobile." },
  { id:"tech_003", node:"node_8", skill:"techniques", type:"mcq", question:"La ginga doit être :", answer:"Fluide et continue", choices:["Rigide","Rapide uniquement","Fluide et continue","Immobile"], explanation:"La ginga doit rester fluide et continue." },
  { id:"tech_004", node:"node_8", skill:"techniques", type:"mcq", question:"Pendant la ginga, les pieds sont :", answer:"Alternés avant/arrière", choices:["Collés","Croisés","Alternés avant/arrière","Toujours parallèles"], explanation:"Pendant la ginga, les pieds s'alternent avant/arrière." },
  { id:"tech_005", node:"node_8", skill:"techniques", type:"mcq", question:"Que signifie « esquiva » ?", answer:"Évitement", choices:["Attaque","Projection","Évitement","Chant"], explanation:"Esquiva signifie évitement." },
  { id:"tech_006", node:"node_8", skill:"techniques", type:"mcq", question:"Quel est le rôle principal d'une esquiva ?", answer:"Éviter une attaque", choices:["Frapper","Chanter","Éviter une attaque","Impressionner"], explanation:"Une esquiva sert principalement à éviter une attaque." },
  { id:"tech_007", node:"node_8", skill:"techniques", type:"mcq", question:"La cocorinha est :", answer:"Une esquive basse accroupie", choices:["Un coup de pied","Une roue","Une esquive basse accroupie","Une projection"], explanation:"La cocorinha est une esquive basse accroupie." },
  { id:"tech_008", node:"node_8", skill:"techniques", type:"mcq", question:"Dans la cocorinha, le pratiquant :", answer:"Se protège en s'abaissant", choices:["Saute","Tourne","Se protège en s'abaissant","Frappe"], explanation:"Dans la cocorinha, on se protège en s'abaissant." },
  { id:"tech_009", node:"node_8", skill:"techniques", type:"mcq", question:"La negativa est :", answer:"Une esquive proche du sol", choices:["Une attaque","Une chute involontaire","Une esquive proche du sol","Une acrobatie"], explanation:"La negativa est une esquive proche du sol." },
  { id:"tech_010", node:"node_8", skill:"techniques", type:"mcq", question:"La negativa se réalise généralement :", answer:"Avec une main au sol", choices:["Debout","En sautant","Avec une main au sol","Allongé"], explanation:"La negativa se réalise généralement avec une main au sol." },
  { id:"tech_011", node:"node_8", skill:"techniques", type:"mcq", question:"Qu'est-ce qu'un au ?", answer:"Roue", choices:["Coup de tête","Esquive","Roue","Balayage"], explanation:"Aú désigne une roue." },
  { id:"tech_012", node:"node_8", skill:"techniques", type:"mcq", question:"Le au ressemble à :", answer:"Une roue gymnastique", choices:["Une roulade","Une fente","Une roue gymnastique","Un saut de grenouille"], explanation:"Le aú ressemble à une roue gymnastique." },
  { id:"tech_013", node:"node_8", skill:"techniques", type:"mcq", question:"Le au est souvent utilisé pour :", answer:"Les trois", choices:["Se déplacer","Attaquer","Esquiver","Les trois"], explanation:"Le aú peut servir à se déplacer, attaquer ou esquiver." },
  { id:"tech_014", node:"node_8", skill:"techniques", type:"mcq", question:"Dans un au classique, le regard est :", answer:"Dirigé vers le partenaire", choices:["Au sol","Fermé","Derrière soi","Dirigé vers le partenaire"], explanation:"Dans un aú classique, on garde le regard vers le partenaire." },
  { id:"tech_015", node:"node_8", skill:"techniques", type:"mcq", question:"La meia-lua de frente est :", answer:"Un coup de pied circulaire", choices:["Une esquive","Une projection","Un coup de pied circulaire","Une roue"], explanation:"La meia-lua de frente est un coup de pied circulaire." },
  { id:"tech_016", node:"node_8", skill:"techniques", type:"mcq", question:"La meia-lua de frente est généralement :", answer:"Un coup de l'avant vers l'extérieur", choices:["Un coup tournant","Un coup de l'avant vers l'extérieur","Un saut","Une projection"], explanation:"La meia-lua de frente part généralement de l'avant vers l'extérieur." },
  { id:"tech_017", node:"node_8", skill:"techniques", type:"mcq", unlock:"lib_queixada", question:"La queixada est :", answer:"Un coup circulaire", choices:["Une esquive","Un coup circulaire","Une roue","Une chute"], explanation:"La queixada est un coup circulaire." },
  { id:"tech_018", node:"node_8", skill:"techniques", type:"mcq", question:"La trajectoire de la queixada est :", answer:"Extérieur vers intérieur", choices:["Intérieur vers extérieur","Extérieur vers intérieur","Verticale","Rectiligne"], explanation:"La trajectoire de la queixada va de l'extérieur vers l'intérieur." },
  { id:"tech_019", node:"node_8", skill:"techniques", type:"mcq", question:"Le martelo est :", answer:"Un coup de pied frappé", choices:["Une projection","Une esquive","Un coup de pied frappé","Une roulade"], explanation:"Le martelo est un coup de pied frappé." },
  { id:"tech_020", node:"node_8", skill:"techniques", type:"mcq", question:"Le martelo est souvent porté avec :", answer:"Le dessus du pied", choices:["Le talon","Le genou","Le dessus du pied","La hanche"], explanation:"Le martelo est souvent porté avec le dessus du pied." },
  { id:"tech_021", node:"node_8", skill:"techniques", type:"mcq", question:"L'armada est :", answer:"Un coup de pied tournant", choices:["Une esquive","Une roue","Un coup de pied tournant","Une projection"], explanation:"L'armada est un coup de pied tournant." },
  { id:"tech_022", node:"node_8", skill:"techniques", type:"mcq", question:"Avant une armada, le pratiquant :", answer:"Tourne sur lui-même", choices:["S'accroupit","Tourne sur lui-même","Saute","Recule"], explanation:"Avant une armada, le pratiquant tourne sur lui-même." },
  { id:"tech_023", node:"node_8", skill:"techniques", type:"mcq", question:"L'armada frappe généralement avec :", answer:"Le talon", choices:["Le genou","La pointe du pied","Le tibia","Le talon"], explanation:"L'armada frappe généralement avec le talon." },
  { id:"tech_024", node:"node_8", skill:"techniques", type:"mcq", question:"Quel mouvement nécessite une rotation complète ?", answer:"Armada", choices:["Cocorinha","Negativa","Martelo","Armada"], explanation:"L'armada nécessite une rotation complète." },
  { id:"tech_025", node:"node_8", skill:"techniques", type:"mcq", question:"Le rolê est :", answer:"Un déplacement au sol", choices:["Une attaque","Un chant","Un déplacement au sol","Une projection"], explanation:"Le rolê est un déplacement au sol." },
  { id:"tech_026", node:"node_8", skill:"techniques", type:"mcq", question:"Le rolê sert souvent à :", answer:"Changer d'angle", choices:["Attaquer","Chanter","Changer d'angle","Arrêter le jeu"], explanation:"Le rolê sert souvent à changer d'angle." },
  { id:"tech_027", node:"node_8", skill:"techniques", type:"mcq", question:"Le rolê est souvent enchaîné avec :", answer:"Une negativa", choices:["Une ladainha","Un chant","Une negativa","Un pandeiro"], explanation:"Le rolê est souvent enchaîné avec une negativa." },
  { id:"tech_028", node:"node_8", skill:"techniques", type:"mcq", question:"Le mouvement « queda de rins » est :", answer:"Un appui sur le coude", choices:["Une attaque","Une esquive","Un appui sur le coude","Une roue"], explanation:"La queda de rins est un appui sur le coude." },
  { id:"tech_029", node:"node_8", skill:"techniques", type:"mcq", question:"La rasteira est :", answer:"Un balayage", choices:["Une roue","Une esquive","Un balayage","Une projection d'épaule"], explanation:"La rasteira est un balayage." },
  { id:"tech_030", node:"node_8", skill:"techniques", type:"mcq", question:"Le but d'une rasteira est :", answer:"Déséquilibrer", choices:["Toucher la tête","Chanter","Déséquilibrer","Tourner"], explanation:"Le but d'une rasteira est de déséquilibrer." },
  { id:"tech_031", node:"node_8", skill:"techniques", type:"mcq", question:"Une rasteira réussie vise principalement :", answer:"Les appuis", choices:["Le bras","La tête","Les appuis","Le dos"], explanation:"Une rasteira vise principalement les appuis." },
  { id:"tech_032", node:"node_8", skill:"techniques", type:"mcq", question:"La rasteira est souvent utilisée contre :", answer:"Un coup de pied", choices:["Une ginga","Un chant","Un coup de pied","Une salutation"], explanation:"La rasteira est souvent utilisée contre un coup de pied." },
  { id:"tech_033", node:"node_8", skill:"techniques", type:"mcq", question:"Le macaco est :", answer:"Une acrobatie arrière", choices:["Une esquive","Une projection","Une acrobatie arrière","Une attaque"], explanation:"Le macaco est une acrobatie arrière." },
  { id:"tech_034", node:"node_8", skill:"techniques", type:"mcq", question:"Le macaco demande généralement :", answer:"Les trois", choices:["De la souplesse","De la force","De la coordination","Les trois"], explanation:"Le macaco demande souplesse, force et coordination." },
  { id:"tech_035", node:"node_8", skill:"techniques", type:"mcq", question:"Le bananeira correspond à :", answer:"Un équilibre sur les mains", choices:["Une roulade","Une roue","Un équilibre sur les mains","Une esquive"], explanation:"Le bananeira correspond à un équilibre sur les mains." },
  { id:"tech_036", node:"node_8", skill:"techniques", type:"mcq", question:"Le bananeira est proche :", answer:"D'un poirier", choices:["D'une cocorinha","D'un martelo","D'une negativa","D'un poirier"], explanation:"Le bananeira est proche d'un poirier." },
  { id:"tech_037", node:"node_8", skill:"techniques", type:"mcq", question:"Pourquoi utilise-t-on les esquives ?", answer:"Pour éviter et préparer une réponse", choices:["Pour se reposer","Pour impressionner","Pour éviter et préparer une réponse","Pour marquer des points"], explanation:"Les esquives permettent d'éviter et de préparer une réponse." },
  { id:"tech_038", node:"node_8", skill:"techniques", type:"mcq", question:"Une bonne capoeira repose davantage sur :", answer:"L'adaptation au partenaire", choices:["La force","La vitesse","L'adaptation au partenaire","La taille"], explanation:"Une bonne capoeira repose sur l'adaptation au partenaire." },
  { id:"tech_039", node:"node_8", skill:"techniques", type:"mcq", question:"Un mouvement spectaculaire est-il toujours efficace ?", answer:"Non", choices:["Oui","Non","Toujours en compétition","Seulement en Angola"], explanation:"Un mouvement spectaculaire n'est pas toujours efficace." },
  { id:"tech_040", node:"node_8", skill:"techniques", type:"mcq", question:"Quel élément est essentiel dans tous les mouvements ?", answer:"Le contrôle", choices:["La force","La souplesse","La vitesse","Le contrôle"], explanation:"Le contrôle est essentiel dans tous les mouvements." },
  { id:"tech_041", node:"node_8", skill:"techniques", type:"mcq", question:"La meia-lua de compasso est :", answer:"Un coup de pied tournant avec les mains au sol", choices:["Une esquive","Une projection","Un coup de pied tournant avec les mains au sol","Une roue"], explanation:"La meia-lua de compasso est un coup de pied tournant avec les mains au sol." },
  { id:"tech_042", node:"node_8", skill:"techniques", type:"mcq", question:"Dans la meia-lua de compasso, le regard se fait souvent :", answer:"Entre les jambes", choices:["Vers le ciel","Vers le sol","Entre les jambes","Derrière soi"], explanation:"Dans la meia-lua de compasso, on regarde souvent entre les jambes." },
  { id:"tech_043", node:"node_8", skill:"techniques", type:"mcq", question:"La surface de frappe principale est :", answer:"Le talon", choices:["Le tibia","La pointe du pied","Le genou","Le talon"], explanation:"La surface de frappe principale est le talon." },
  { id:"tech_044", node:"node_8", skill:"techniques", type:"mcq", question:"La meia-lua de compasso est réputée pour :", answer:"Être puissante", choices:["Être lente","Être décorative","Être puissante","Être uniquement défensive"], explanation:"La meia-lua de compasso est réputée pour sa puissance." },
  { id:"tech_045", node:"node_8", skill:"techniques", type:"mcq", question:"La chapa est :", answer:"Un coup de pied poussé", choices:["Un balayage","Une esquive","Un coup de pied poussé","Une projection"], explanation:"La chapa est un coup de pied poussé." },
  { id:"tech_046", node:"node_8", skill:"techniques", type:"mcq", question:"La chapa est souvent utilisée pour :", answer:"Les trois", choices:["Créer de la distance","Déséquilibrer","Stopper une avancée","Les trois"], explanation:"La chapa peut créer de la distance, déséquilibrer ou stopper une avancée." },
  { id:"tech_047", node:"node_8", skill:"techniques", type:"mcq", question:"La frappe de la chapa se fait principalement avec :", answer:"La plante du pied", choices:["Le talon","Le tibia","La pointe","La plante du pied"], explanation:"La chapa frappe principalement avec la plante du pied." },
  { id:"tech_048", node:"node_8", skill:"techniques", type:"mcq", question:"La chapa est généralement :", answer:"Directe", choices:["Circulaire","Tournante","Directe","Acrobatique"], explanation:"La chapa est généralement directe." },
  { id:"tech_049", node:"node_8", skill:"techniques", type:"mcq", question:"La ponteira est :", answer:"Un coup de pied direct", choices:["Un balayage","Une esquive","Une projection","Un coup de pied direct"], explanation:"La ponteira est un coup de pied direct." },
  { id:"tech_050", node:"node_8", skill:"techniques", type:"mcq", question:"La ponteira utilise principalement :", answer:"La pointe du pied", choices:["Le talon","Le tibia","La pointe du pied","Le genou"], explanation:"La ponteira utilise principalement la pointe du pied." },
  { id:"tech_051", node:"node_8", skill:"techniques", type:"mcq", question:"La ponteira ressemble le plus à :", answer:"Un coup de pied frontal", choices:["Une roue","Une cocorinha","Une rasteira","Un coup de pied frontal"], explanation:"La ponteira ressemble à un coup de pied frontal." },
  { id:"tech_052", node:"node_8", skill:"techniques", type:"mcq", question:"La ponteira vise souvent :", answer:"Le centre du corps", choices:["Les appuis","Le sol","Le centre du corps","Les mains"], explanation:"La ponteira vise souvent le centre du corps." },
  { id:"tech_053", node:"node_8", skill:"techniques", type:"mcq", question:"La cabeçada est :", answer:"Un coup de tête", choices:["Une esquive","Une roue","Un coup de tête","Une projection"], explanation:"La cabeçada est un coup de tête." },
  { id:"tech_054", node:"node_8", skill:"techniques", type:"mcq", question:"La cabeçada est un mouvement :", answer:"Traditionnel", choices:["Moderne","Sportif","Traditionnel","Acrobatique"], explanation:"La cabeçada est un mouvement traditionnel." },
  { id:"tech_055", node:"node_8", skill:"techniques", type:"mcq", question:"Historiquement, la cabeçada était utilisée :", answer:"Comme attaque rapprochée", choices:["Pour saluer","Pour chanter","Comme attaque rapprochée","Pour esquiver"], explanation:"Historiquement, la cabeçada servait comme attaque rapprochée." },
  { id:"tech_056", node:"node_8", skill:"techniques", type:"mcq", question:"La cabeçada est davantage associée :", answer:"Au jeu traditionnel", choices:["Aux acrobaties","Aux instruments","Au jeu traditionnel","Aux compétitions"], explanation:"La cabeçada est davantage associée au jeu traditionnel." },
  { id:"tech_057", node:"node_8", skill:"techniques", type:"mcq", question:"Tesoura signifie :", answer:"Ciseaux", choices:["Balayage","Marteau","Tête","Ciseaux"], explanation:"Tesoura signifie ciseaux." },
  { id:"tech_058", node:"node_8", skill:"techniques", type:"mcq", question:"La tesoura cherche principalement à :", answer:"Faire tomber l'adversaire", choices:["Frapper","Chanter","Faire tomber l'adversaire","Sauter"], explanation:"La tesoura cherche principalement à faire tomber l'adversaire." },
  { id:"tech_059", node:"node_8", skill:"techniques", type:"mcq", question:"La tesoura utilise :", answer:"Les jambes", choices:["Les bras","Une main","La tête","Les jambes"], explanation:"La tesoura utilise les jambes." },
  { id:"tech_060", node:"node_8", skill:"techniques", type:"mcq", question:"La tesoura est :", answer:"Une technique d'immobilisation ou de projection", choices:["Un chant","Une esquive","Une technique d'immobilisation ou de projection","Une salutation"], explanation:"La tesoura est une technique d'immobilisation ou de projection." },
  { id:"tech_061", node:"node_8", skill:"techniques", type:"mcq", question:"La vingativa est :", answer:"Une projection", choices:["Une roue","Un chant","Une projection","Une esquive"], explanation:"La vingativa est une projection." },
  { id:"tech_062", node:"node_8", skill:"techniques", type:"mcq", question:"La vingativa cherche principalement à :", answer:"Projeter le partenaire", choices:["Toucher le visage","Déséquilibrer","Chanter","Projeter le partenaire"], explanation:"La vingativa cherche principalement à projeter le partenaire." },
  { id:"tech_063", node:"node_8", skill:"techniques", type:"mcq", question:"La vingativa est souvent enseignée :", answer:"Après les bases", choices:["Très tôt","Jamais","Après les bases","Seulement aux mestres"], explanation:"La vingativa est souvent enseignée après les bases." },
  { id:"tech_064", node:"node_8", skill:"techniques", type:"mcq", question:"La vingativa est davantage :", answer:"Une technique de corps à corps", choices:["Une frappe","Une esquive","Une technique de corps à corps","Une acrobatie"], explanation:"La vingativa est une technique de corps à corps." },
  { id:"tech_065", node:"node_8", skill:"techniques", type:"mcq", question:"Un floreio est :", answer:"Un mouvement esthétique", choices:["Une attaque","Un rythme","Un mouvement esthétique","Une esquive"], explanation:"Un floreio est un mouvement esthétique." },
  { id:"tech_066", node:"node_8", skill:"techniques", type:"mcq", question:"Les floreios servent principalement :", answer:"À enrichir le jeu", choices:["À gagner des points","À remplacer la ginga","À enrichir le jeu","À diriger la musique"], explanation:"Les floreios servent à enrichir le jeu." },
  { id:"tech_067", node:"node_8", skill:"techniques", type:"mcq", question:"Le macaco est souvent considéré comme :", answer:"Un floreio", choices:["Une esquive","Une projection","Un chant","Un floreio"], explanation:"Le macaco est souvent considéré comme un floreio." },
  { id:"tech_068", node:"node_8", skill:"techniques", type:"mcq", question:"Un floreio doit être :", answer:"Contrôlé", choices:["Rapide uniquement","Fort uniquement","Contrôlé","Dangereux"], explanation:"Un floreio doit être contrôlé." },
  { id:"tech_069", node:"node_8", skill:"techniques", type:"mcq", question:"La queda de quatro est :", answer:"Une position basse d'appui", choices:["Une attaque","Une roue","Une position basse d'appui","Une projection"], explanation:"La queda de quatro est une position basse d'appui." },
  { id:"tech_070", node:"node_8", skill:"techniques", type:"mcq", question:"La queda de quatro sert souvent :", answer:"À préparer une transition", choices:["À attaquer immédiatement","À chanter","À préparer une transition","À quitter la roda"], explanation:"La queda de quatro sert souvent à préparer une transition." },
  { id:"tech_071", node:"node_8", skill:"techniques", type:"mcq", question:"Une esquive réussie permet souvent :", answer:"De contre-attaquer", choices:["De perdre l'initiative","De quitter le jeu","De contre-attaquer","De ralentir la musique"], explanation:"Une esquive réussie permet souvent de contre-attaquer." },
  { id:"tech_072", node:"node_8", skill:"techniques", type:"mcq", question:"Le meilleur moment pour une rasteira est souvent :", answer:"Quand il est sur un appui", choices:["Quand l'adversaire est stable","Pendant une pause","Quand il est sur un appui","Pendant un chant"], explanation:"Le meilleur moment pour une rasteira est souvent quand le partenaire est sur un appui." },
  { id:"tech_073", node:"node_8", skill:"techniques", type:"mcq", question:"Une bonne malícia consiste à :", answer:"Faire croire une chose et en faire une autre", choices:["Jouer vite","Jouer fort","Faire croire une chose et en faire une autre","Jouer sans musique"], explanation:"La malícia consiste souvent à faire croire une chose et en faire une autre." },
  { id:"tech_074", node:"node_8", skill:"techniques", type:"mcq", question:"Pourquoi regarde-t-on constamment son partenaire ?", answer:"Pour anticiper ses intentions", choices:["Pour le copier","Pour le juger","Pour anticiper ses intentions","Pour le distraire"], explanation:"On regarde son partenaire pour anticiper ses intentions." },
  { id:"tech_075", node:"node_8", skill:"techniques", type:"mcq", question:"La capoeira valorise davantage :", answer:"Le dialogue du jeu", choices:["La domination","La violence","La compétition","Le dialogue du jeu"], explanation:"La capoeira valorise le dialogue du jeu." },
  { id:"tech_076", node:"node_8", skill:"techniques", type:"mcq", question:"Un coup évité proprement est souvent :", answer:"Une réussite du jeu", choices:["Un échec","Une faute","Une réussite du jeu","Une pénalité"], explanation:"Un coup évité proprement est une réussite du jeu." },
  { id:"tech_077", node:"node_8", skill:"techniques", type:"mcq", question:"L'objectif principal d'une roda n'est pas :", answer:"Mettre KO son partenaire", choices:["Apprendre","Jouer","Échanger","Mettre KO son partenaire"], explanation:"L'objectif principal d'une roda n'est pas de mettre KO son partenaire." },
  { id:"tech_078", node:"node_8", skill:"techniques", type:"mcq", question:"Un capoeiriste expérimenté se reconnaît souvent à :", answer:"Sa lecture du jeu", choices:["Sa force","Son poids","Sa vitesse","Sa lecture du jeu"], explanation:"Un capoeiriste expérimenté se reconnaît souvent à sa lecture du jeu." },
  { id:"tech_079", node:"node_8", skill:"techniques", type:"mcq", question:"La lecture du jeu correspond à :", answer:"Comprendre les intentions du partenaire", choices:["Lire les paroles","Lire le rythme","Comprendre les intentions du partenaire","Observer les spectateurs"], explanation:"La lecture du jeu consiste à comprendre les intentions du partenaire." },
  { id:"tech_080", node:"node_8", skill:"techniques", type:"mcq", question:"Quelle qualité résume le mieux un bon capoeiriste ?", answer:"Adaptabilité", choices:["Force","Souplesse","Vitesse","Adaptabilité"], explanation:"L'adaptabilité résume très bien un bon capoeiriste." },

  { id:"toque_001", node:"node_9", skill:"berimbau", type:"mcq", question:"Comment appelle-t-on un rythme joué au berimbau ?", answer:"Un toque", choices:["Une roda","Une ladainha","Un corrido","Un toque"], explanation:"Un rythme joué au berimbau s'appelle un toque." },
  { id:"toque_002", node:"node_9", skill:"berimbau", type:"mcq", question:"Quel instrument détermine principalement le rythme du jeu ?", answer:"Berimbau", choices:["Atabaque","Pandeiro","Agogo","Berimbau"], explanation:"Le berimbau détermine principalement le rythme du jeu." },
  { id:"toque_003", node:"node_9", skill:"berimbau", type:"mcq", question:"Le rythme influence :", answer:"La manière de jouer", choices:["La couleur des cordes","Le chant uniquement","Le matériel utilisé","La manière de jouer"], explanation:"Le rythme influence la manière de jouer." },
  { id:"toque_004", node:"node_9", skill:"berimbau", type:"mcq", question:"Un même jeu peut-il changer si le toque change ?", answer:"Oui", choices:["Non","Seulement en compétition","Seulement pour les débutants","Oui"], explanation:"Un même jeu peut changer si le toque change." },
  { id:"toque_005", node:"node_9", skill:"berimbau", type:"mcq", question:"Quel rythme est souvent associé à un jeu plus lent et traditionnel ?", answer:"Angola", choices:["São Bento Grande","Cavalaria","Iuna","Angola"], explanation:"Angola est souvent associé à un jeu plus lent et traditionnel." },
  { id:"toque_006", node:"node_9", skill:"berimbau", type:"mcq", question:"Le toque Angola favorise généralement :", answer:"La malícia", choices:["Les sauts","La vitesse","Les acrobaties uniquement","La malícia"], explanation:"Le toque Angola favorise généralement la malícia." },
  { id:"toque_007", node:"node_9", skill:"berimbau", type:"mcq", question:"Quel rythme est souvent plus rapide ?", answer:"São Bento Grande", choices:["Angola","Iuna","Santa Maria","São Bento Grande"], explanation:"São Bento Grande est souvent plus rapide." },
  { id:"toque_008", node:"node_9", skill:"berimbau", type:"mcq", question:"Quand le rythme accélère, le jeu devient souvent :", answer:"Plus dynamique", choices:["Plus lent","Plus statique","Plus silencieux","Plus dynamique"], explanation:"Quand le rythme accélère, le jeu devient souvent plus dynamique." },
  { id:"toque_009", node:"node_9", skill:"berimbau", type:"mcq", question:"Le toque peut-il modifier l'énergie de la roda ?", answer:"Oui", choices:["Non","Rarement","Seulement avec plusieurs berimbaus","Oui"], explanation:"Le toque peut modifier l'énergie de la roda." },
  { id:"toque_010", node:"node_9", skill:"berimbau", type:"mcq", question:"Pourquoi apprendre les toques ?", answer:"Pour comprendre le jeu", choices:["Pour avoir une corde","Pour arbitrer","Pour chanter mieux","Pour comprendre le jeu"], explanation:"Apprendre les toques aide à comprendre le jeu." },

  { id:"toque_011", node:"node_9", skill:"berimbau", type:"mcq", question:"Le toque Angola est généralement :", answer:"Traditionnel", choices:["Rapide","Sportif","Aérien","Traditionnel"], explanation:"Le toque Angola est généralement traditionnel." },
  { id:"toque_012", node:"node_9", skill:"berimbau", type:"mcq", question:"Le toque São Bento Grande est souvent associé :", answer:"Toutes ces réponses", choices:["Aux jeux rapides","Aux jeux modernes","À davantage d'énergie","Toutes ces réponses"], explanation:"São Bento Grande peut être associé aux jeux rapides, modernes et plus énergiques." },
  { id:"toque_013", node:"node_9", skill:"berimbau", type:"mcq", question:"Le toque Iuna est historiquement joué :", answer:"Pour les joueurs expérimentés", choices:["Pour les débutants","Pour les enfants","Pour les spectateurs","Pour les joueurs expérimentés"], explanation:"Iuna est historiquement joué pour les joueurs expérimentés." },
  { id:"toque_014", node:"node_9", skill:"berimbau", type:"mcq", question:"Le toque Cavalaria servait autrefois à :", answer:"Donner l'alerte", choices:["Commencer la roda","Jouer entre mestres","Faire danser","Donner l'alerte"], explanation:"Cavalaria servait autrefois à donner l'alerte." },
  { id:"toque_015", node:"node_9", skill:"berimbau", type:"mcq", question:"Pourquoi le toque Cavalaria était-il utile ?", answer:"Pour prévenir l'arrivée de la police", choices:["Pour annoncer les repas","Pour trouver les instruments","Pour régler les conflits","Pour prévenir l'arrivée de la police"], explanation:"Cavalaria servait à prévenir l'arrivée de la police." },
  { id:"toque_016", node:"node_9", skill:"berimbau", type:"mcq", question:"Le toque Benguela est souvent associé à :", answer:"Toutes ces réponses", choices:["Un jeu intermédiaire","Un jeu technique","Un jeu fluide","Toutes ces réponses"], explanation:"Benguela est souvent associé à un jeu intermédiaire, technique et fluide." },
  { id:"toque_017", node:"node_9", skill:"berimbau", type:"mcq", question:"Le toque Santa Maria est historiquement lié :", answer:"Aux échanges commerciaux et au jeu", choices:["Aux compétitions","Aux démonstrations","Aux rodas d'enfants","Aux échanges commerciaux et au jeu"], explanation:"Santa Maria est historiquement lié aux échanges commerciaux et au jeu." },
  { id:"toque_018", node:"node_9", skill:"berimbau", type:"mcq", question:"Le toque Iuna comporte généralement :", answer:"Peu ou pas de chant", choices:["Beaucoup de chants","Uniquement des corridos","Uniquement des pandeiros","Peu ou pas de chant"], explanation:"Iuna comporte généralement peu ou pas de chant." },
  { id:"toque_019", node:"node_9", skill:"berimbau", type:"mcq", question:"Quel toque est souvent choisi pour travailler la technique ?", answer:"Benguela", choices:["Cavalaria","Angola uniquement","Santa Maria","Benguela"], explanation:"Benguela est souvent choisi pour travailler la technique." },
  { id:"toque_020", node:"node_9", skill:"berimbau", type:"mcq", question:"Le rythme du berimbau doit être :", answer:"Écouté", choices:["Ignoré","Subi","Contredit","Écouté"], explanation:"Le rythme du berimbau doit être écouté." },

  { id:"toque_021", node:"node_9", skill:"berimbau", type:"mcq", question:"Si le toque ralentit fortement, il est souvent judicieux :", answer:"D'adapter son jeu", choices:["D'accélérer","D'ignorer le rythme","De quitter la roda","D'adapter son jeu"], explanation:"Si le toque ralentit, il faut adapter son jeu." },
  { id:"toque_022", node:"node_9", skill:"berimbau", type:"mcq", question:"Un bon capoeiriste écoute :", answer:"Le partenaire et la musique", choices:["Seulement son partenaire","Seulement le chant","Seulement le berimbau","Le partenaire et la musique"], explanation:"Un bon capoeiriste écoute le partenaire et la musique." },
  { id:"toque_023", node:"node_9", skill:"berimbau", type:"mcq", question:"Quel élément guide le plus la roda ?", answer:"Le berimbau principal", choices:["Les spectateurs","Les professeurs","Les pandeiros","Le berimbau principal"], explanation:"Le berimbau principal guide le plus la roda." },
  { id:"toque_024", node:"node_9", skill:"berimbau", type:"mcq", question:"Le gunga joue souvent :", answer:"La base du rythme", choices:["Les variations","Les improvisations","Les acrobaties","La base du rythme"], explanation:"Le gunga joue souvent la base du rythme." },
  { id:"toque_025", node:"node_9", skill:"berimbau", type:"mcq", question:"Le viola joue souvent :", answer:"Les variations", choices:["Les graves","Les bases uniquement","Les chants","Les variations"], explanation:"La viola joue souvent les variations." },
  { id:"toque_026", node:"node_9", skill:"berimbau", type:"mcq", question:"Le médio sert souvent :", answer:"À soutenir le rythme", choices:["À improviser","À chanter","À ralentir","À soutenir le rythme"], explanation:"Le médio sert souvent à soutenir le rythme." },
  { id:"toque_027", node:"node_9", skill:"berimbau", type:"mcq", question:"Pourquoi les trois berimbaus sont-ils utiles ?", answer:"Pour enrichir la musique", choices:["Pour faire plus de bruit","Pour décorer","Pour impressionner","Pour enrichir la musique"], explanation:"Les trois berimbaus enrichissent la musique." },
  { id:"toque_028", node:"node_9", skill:"berimbau", type:"mcq", question:"Quand un toque change, un capoeiriste doit :", answer:"Adapter son jeu", choices:["Continuer pareil","Quitter la roda","Changer d'instrument","Adapter son jeu"], explanation:"Quand un toque change, il faut adapter son jeu." },
  { id:"toque_029", node:"node_9", skill:"berimbau", type:"mcq", question:"La compréhension des toques améliore :", answer:"Toutes ces réponses", choices:["La lecture du jeu","Le timing","L'adaptation","Toutes ces réponses"], explanation:"Comprendre les toques améliore la lecture du jeu, le timing et l'adaptation." },
  { id:"toque_030", node:"node_9", skill:"berimbau", type:"mcq", question:"Quelle affirmation est vraie ?", answer:"Chaque toque possède sa propre identité", choices:["Tous les toques produisent le même jeu","Les toques sont secondaires","Le rythme n'influence pas la roda","Chaque toque possède sa propre identité"], explanation:"Chaque toque possède sa propre identité." },

  { id:"q071", node:"song_bank", skill:"chants", type:"hole", question:"Complète le couplet.", text:"Marinheiro só,\nMarinheiro só,\nQuem te ensinou a {nadar}?", holes:[{answer:"nadar", choices:["nadar","cantar","jogar","tocar"]}], explanation:"« Quem te ensinou a nadar ? » signifie « Qui t’a appris à nager ? »." },
  { id:"q072", node:"song_bank", skill:"chants", type:"mcq", question:"« Quem te ensinou a nadar ? » signifie…", answer:"Qui t’a appris à nager ?", choices:["Qui t’a appris à nager ?","Où est le bateau ?","Qui chante ?","Pourquoi jouer ?"], explanation:"Quem = qui, ensinou = a appris, nadar = nager." },
  { id:"q073", node:"song_bank", skill:"chants", type:"hole", question:"Complète plusieurs trous.", text:"Iê viva meu {mestre},\nIê viva meu mestre, {camará}", holes:[{answer:"mestre", choices:["mestre","dobrao","jogo","arame"]},{answer:"camará", choices:["camará","Paraná","caxixi","ginga"]}], explanation:"On travaille ici une phrase complète, pas seulement un mot isolé." },
  { id:"q074", node:"song_bank", skill:"chants", type:"order", question:"Remets ce mini-couplet dans l’ordre.", lines:["Marinheiro só","Marinheiro só","Quem te ensinou","A nadar?"], correct:["Marinheiro só","Marinheiro só","Quem te ensinou","A nadar?"], explanation:"L’ordre aide à mémoriser le chant comme une séquence." },
  { id:"q075", node:"song_bank", skill:"chants", type:"hole", question:"Complète la phrase de couplet.", text:"Zum, zum, zum,\n{capoeira} mata um", holes:[{answer:"capoeira", choices:["capoeira","berimbau","cabaça","mandinga"]}], explanation:"Ce chant existe avec des variantes selon les groupes." },
  { id:"q076", node:"song_bank", skill:"chants", type:"mcq", question:"Pour apprendre un chant, il vaut mieux retenir…", answer:"Le refrain, le sens et les réponses du chœur", choices:["Le refrain, le sens et les réponses du chœur","Seulement le titre","Seulement le premier mot","Uniquement le rythme"], explanation:"Comprendre la structure aide à participer." },
  { id:"q077", node:"song_bank", skill:"chants", type:"hole", question:"Complète ce passage.", text:"Paranauê, Paranauê,\nParanauê, {Paraná}", holes:[{answer:"Paraná", choices:["Paraná","camará","Angola","mestre"]}], explanation:"La répétition du refrain construit la mémoire." },
  { id:"q078", node:"song_bank", skill:"chants", type:"mcq", question:"Dans un texte à trou de chant, l’objectif est surtout…", answer:"Mémoriser les phrases utiles en roda", choices:["Mémoriser les phrases utiles en roda","Faire de la grammaire pure","Éviter le chant","Remplacer l’écoute"], explanation:"Le texte à trou prépare au chant réel." },
  { id:"q079", node:"song_bank", skill:"chants", type:"match", question:"Associe portugais et français.", pairs:[["nadar","nager"],["cantar","chanter"],["jogar","jouer"]], explanation:"Le portugais aide à comprendre les chants." },
  { id:"q080", node:"song_bank", skill:"chants", type:"mcq", question:"Un chant peut varier selon…", answer:"Les groupes, mestres et traditions", choices:["Les groupes, mestres et traditions","La météo uniquement","Le téléphone utilisé","La couleur du sol"], explanation:"Il existe souvent plusieurs versions d’un même chant." },

  { id:"q081", node:"song_bank", skill:"culture", type:"mcq", question:"Mestre Bimba est souvent associé à…", answer:"La capoeira régionale", choices:["La capoeira régionale","La cabaça","Un chant français","Un téléphone"], explanation:"Mestre Bimba est une figure majeure de la capoeira régionale." },
  { id:"q082", node:"song_bank", skill:"culture", type:"mcq", question:"Mestre Pastinha est souvent associé à…", answer:"La capoeira Angola", choices:["La capoeira Angola","Le football","Le judo","La bateria électronique"], explanation:"Mestre Pastinha est une figure majeure de la capoeira Angola." },
  { id:"q083", node:"song_bank", skill:"culture", type:"mcq", question:"La capoeira est liée historiquement au Brésil et à…", answer:"L’histoire afro-brésilienne", choices:["L’histoire afro-brésilienne","La mythologie grecque uniquement","La boxe anglaise uniquement","La chevalerie médiévale"], explanation:"La capoeira est profondément liée aux cultures afro-brésiliennes." },
  { id:"q084", node:"song_bank", skill:"culture", type:"mcq", question:"Le respect dans la roda concerne…", answer:"Les partenaires, la musique et les traditions", choices:["Les partenaires, la musique et les traditions","Seulement la victoire","Seulement les acrobaties","Seulement le public"], explanation:"La roda est un espace collectif." },
  { id:"q085", node:"song_bank", skill:"culture", type:"mcq", question:"La malícia désigne plutôt…", answer:"L’intelligence rusée du jeu", choices:["L’intelligence rusée du jeu","La violence gratuite","Un instrument","Une tenue"], explanation:"La malícia est liée à la ruse et au décalage." },
  { id:"q086", node:"song_bank", skill:"culture", type:"mcq", question:"La chamada est…", answer:"Un appel ou moment particulier dans certains jeux", choices:["Un appel ou moment particulier dans certains jeux","Une pierre","Une chaussure","Un tambour"], explanation:"La chamada existe notamment dans certains contextes de jeu." },
  { id:"q087", node:"song_bank", skill:"culture", type:"mcq", question:"L’histoire des chants est importante car…", answer:"Elle donne du sens à ce que l’on chante", choices:["Elle donne du sens à ce que l’on chante","Elle remplace l’entraînement","Elle interdit la roda","Elle supprime le portugais"], explanation:"Comprendre un chant change la manière de le chanter." },
  { id:"q088", node:"song_bank", skill:"culture", type:"mcq", question:"Une application théorique doit rester…", answer:"Un complément du cours", choices:["Un complément du cours","Un substitut total au mestre","Un système de grades officiel","Un arbitre de roda"], explanation:"La pratique vivante reste au cœur de la capoeira." },
  { id:"q089", node:"song_bank", skill:"culture", type:"mcq", question:"La transmission en capoeira passe par…", answer:"Le corps, la musique, l’oralité et la communauté", choices:["Le corps, la musique, l’oralité et la communauté","Uniquement des livres","Uniquement des scores","Uniquement des vidéos"], explanation:"La capoeira se transmet dans une pratique collective." },
  { id:"q090", node:"song_bank", skill:"culture", type:"match", question:"Associe les notions.", pairs:[["Bimba","Régionale"],["Pastinha","Angola"],["Roda","Cercle"]], explanation:"Ces repères culturels sont fondamentaux." },

  { id:"q091", node:"node_10", skill:"mixed", type:"mcq", question:"DONG correspond plutôt à…", answer:"Son ouvert", choices:["Son ouvert","Son fermé","Son bourdonné","Un chant"], explanation:"DONG représente le son ouvert." },
  { id:"q092", node:"node_10", skill:"mixed", type:"mcq", question:"TCHIN correspond plutôt à…", answer:"Son fermé", choices:["Son fermé","Son ouvert","Son bourdonné","Une esquive"], explanation:"TCHIN représente le son fermé." },
  { id:"q093", node:"node_10", skill:"mixed", type:"mcq", question:"BZZZ correspond plutôt à…", answer:"Son bourdonné", choices:["Son bourdonné","Son ouvert","Son fermé","Un grade"], explanation:"BZZZ représente le son bourdonné." },
  { id:"q094", node:"node_10", skill:"mixed", type:"hole", question:"Complète.", text:"Paranauê, Paranauê,\n{Paraná}", holes:[{answer:"Paraná", choices:["Paraná","caxixi","mestre","jogo"]}], explanation:"Révision du refrain." },
  { id:"q095", node:"node_10", skill:"mixed", type:"mcq", question:"Le dobrão sert à…", answer:"Modifier le son de l’arame", choices:["Modifier le son de l’arame","Amplifier la voix","Remplacer le caxixi","Changer de chant"], explanation:"Le dobrão est essentiel pour produire les différents sons." },
  { id:"q096", node:"node_10", skill:"mixed", type:"mcq", question:"La queixada est…", answer:"Un coup de pied circulaire", choices:["Un coup de pied circulaire","Une pierre","Un chant","Un instrument"], explanation:"Révision technique." },
  { id:"q097", node:"node_10", skill:"mixed", type:"mcq", question:"Angola est souvent…", answer:"Lent, bas et stratégique", choices:["Lent, bas et stratégique","Rapide uniquement","Sans musique","Sans jeu"], explanation:"Révision toque/style." },
  { id:"q098", node:"node_10", skill:"mixed", type:"mcq", question:"« Camará » signifie…", answer:"Camarade", choices:["Camarade","Cabaça","Corde","Chute"], explanation:"Révision portugais." },
  { id:"q099", node:"node_10", skill:"mixed", type:"order", question:"Remets dans l’ordre : ouvert, fermé, bourdonné.", lines:["DONG","TCHIN","BZZZ"], correct:["DONG","TCHIN","BZZZ"], explanation:"Révision des sons." },
  { id:"q100", node:"node_10", skill:"mixed", type:"match", question:"Associe.", pairs:[["Dobrão","Pierre/pièce"],["Cabaça","Résonance"],["Baqueta","Frappe"]], explanation:"Révision berimbau." },

  { id:"q101", node:"node_1", skill:"chants", type:"hole", unlock:"lib_song_refrain", question:"Complète le refrain de « A Maré Tá Cheia ».", text:"A maré 'tá cheia, {ioió}\nA maré 'tá cheia, iaiá!", holes:[{answer:"ioió", choices:["ioió","camará","berimbau","mandinga"]}], explanation:"Le refrain alterne ioió et iaiá." },
  { id:"q102", node:"node_1", skill:"chants", type:"hole", question:"Complète la réponse du chœur.", text:"A maré 'tá cheia, ioió\nA maré 'tá cheia, {iaiá}!", holes:[{answer:"iaiá", choices:["iaiá","ginga","patuá","caxixi"]}], explanation:"La réponse est iaiá après ioió." },
  { id:"q103", node:"node_1", skill:"chants", type:"match", question:"Associe les mouvements de la maré.", pairs:[["A maré subiu","Sobe maré"],["A maré desceu","Desce maré"],["O peixe pulou","Na maré"]], explanation:"Le chant joue sur monter, descendre et sauter dans la maré." },
  { id:"q104", node:"node_1", skill:"chants", type:"order", question:"Remets ces lignes dans l'ordre.", lines:["A maré subiu","Sobe maré","A maré desceu","Desce maré"], correct:["A maré subiu","Sobe maré","A maré desceu","Desce maré"], explanation:"Subiu appelle sobe, puis desceu appelle desce." },
  { id:"q105", node:"node_1", skill:"chants", type:"mcq", question:"Dans « A Maré Tá Cheia », quelle image revient à la fin ?", answer:"Le poisson qui saute dans la maré", choices:["Le poisson qui saute dans la maré","Le berimbau qui se casse","Le mestre qui dit non","La feuille qui craque"], explanation:"La phrase répétée est « Olha o peixe pulou na maré »." },
  { id:"q106", node:"node_1", skill:"chants", type:"hole", question:"Complète la ligne.", text:"Vou pra Ilha de {Maré}!", holes:[{answer:"Maré", choices:["Maré","Bahia","Angola","Paraná"]}], explanation:"La ligne nomme l'Ilha de Maré." },
  { id:"q107", node:"node_1", skill:"chants", type:"mcq", question:"Quand le chant dit « A maré subiu », quelle réponse suit ?", answer:"Sobe maré", choices:["Sobe maré","Desce maré","Iaiá","Vou pra Ilha"], explanation:"Subiu correspond à sobe maré." },
  { id:"q108", node:"node_1", skill:"chants", type:"mcq", question:"Quand le chant dit « A maré desceu », quelle réponse suit ?", answer:"Desce maré", choices:["Sobe maré","Desce maré","Ioió","Peixe pulou"], explanation:"Desceu correspond à desce maré." },
  { id:"q109", node:"node_1", skill:"chants", type:"hole", question:"Complète l'alternance du refrain.", text:"A maré 'tá cheia, ioió\nA maré 'tá cheia, {iaiá}!", holes:[{answer:"iaiá", choices:["ioió","iaiá"]}], explanation:"Après ioió, la réponse du refrain est iaiá." },
  { id:"q110", node:"node_1", skill:"chants", type:"speak", question:"Parle ou chante cette ligne.", prompt:"A maré tá cheia, ioió", answer:"A maré tá cheia ioió", accept:["A mare ta cheia ioio","A maré está cheia ioió"], explanation:"Boa. L'objectif est d'oser dire la phrase du refrain." },

  { id:"q111", node:"node_2", skill:"chants", type:"hole", unlock:"lib_mandinga", question:"Complète le son entendu dans « Folha Seca ».", text:"Eu pisei na folha seca\nE ouvi fazer: {chuê chua}", holes:[{answer:"chuê chua", choices:["chuê chua","sim sim sim","sobe maré","ABC"]}], explanation:"Le chant imite le bruit de la feuille avec « chuê chua »." },
  { id:"q112", node:"node_2", skill:"chants", type:"hole", question:"Complète la réponse sonore.", text:"Chuê chuê chuê {chua}", holes:[{answer:"chua", choices:["chua","ioió","não","au"]}], explanation:"La réponse finit par chua." },
  { id:"q113", node:"node_2", skill:"chants", type:"mcq", question:"Dans « Folha Seca », que ne porte pas celui qui ne peut pas avec mandinga ?", answer:"Patuá", choices:["Patuá","Cabaça","Dobrão","Baqueta"], explanation:"La ligne dit: « Quem não pode com mandinga, não carrega patuá »." },
  { id:"q114", node:"node_2", skill:"chants", type:"match", question:"Associe les mots du chant.", pairs:[["Folha seca","Feuille sèche"],["Mandinga","Malice/ruse"],["Patuá","Amulette"]], explanation:"Ces repères donnent du sens au chant." },
  { id:"q115", node:"node_2", skill:"chants", type:"order", question:"Remets le début de « Folha Seca » dans l'ordre.", lines:["Eu pisei na folha seca","E ouvi fazer: chuê chua","Chuê chuê chuê chua","Ouvi fazer, chuê chua"], correct:["Eu pisei na folha seca","E ouvi fazer: chuê chua","Chuê chuê chuê chua","Ouvi fazer, chuê chua"], explanation:"Le début installe l'image, puis la réponse sonore." },
  { id:"q116", node:"node_2", skill:"chants", type:"mcq", question:"Avec quel mot du chant associe-t-on Besouro ?", answer:"Manganga", choices:["Manganga","Berimbau","Maré","Lampião"], explanation:"La ligne associe Besouro et Mangangá." },
  { id:"q117", node:"node_2", skill:"chants", type:"hole", question:"Complète la ligne.", text:"Na casa do batuqueiro quero ver tu {mandingar}", holes:[{answer:"mandingar", choices:["mandingar","cantar","descer","aprender"]}], explanation:"La ligne finit par mandingar." },
  { id:"q118", node:"node_2", skill:"chants", type:"mcq", question:"Quelle phrase appartient à « Folha Seca » ?", answer:"Eu pisei na folha seca", choices:["Eu pisei na folha seca","Mas hoje tem amanhã não","É o C de capoeira","A maré subiu"], explanation:"C'est la première image du chant." },
  { id:"q119", node:"node_2", skill:"chants", type:"hole", question:"Complète la ligne.", text:"Joga nego para {cima}", holes:[{answer:"cima", choices:["cima","baixo","maré","roda"]}], explanation:"La ligne dit « Joga nego para cima »." },
  { id:"q120", node:"node_2", skill:"chants", type:"speak", question:"Parle ou chante cette réponse.", prompt:"Chuê chuê chuê chua", answer:"Chuê chuê chuê chua", accept:["Chue chue chue chua"], explanation:"Boa. Cette réponse sonore doit devenir automatique." },

  { id:"q121", node:"node_3", skill:"chants", type:"hole", question:"Complète le refrain de « Oi Sim Sim Sim ».", text:"Oi sim sim sim\nOi {não não não}", holes:[{answer:"não não não", choices:["não não não","sobe maré","chuê chua","berimbau"]}], explanation:"Le refrain alterne oui et non: sim puis não." },
  { id:"q122", node:"node_3", skill:"chants", type:"match", question:"Associe les mots portugais du chant.", pairs:[["Sim","Oui"],["Não","Non"],["Hoje","Aujourd'hui"]], explanation:"Ces trois mots suffisent déjà à comprendre le refrain." },
  { id:"q123", node:"node_3", skill:"chants", type:"mcq", question:"Dans « Oi Sim Sim Sim », si le mestre dit oui, le chant demande…", answer:"Qui osera dire non", choices:["Qui osera dire non","Qui a pris le berimbau","Où est la maré","Pourquoi la feuille tombe"], explanation:"La phrase dit: « Quero ver quem diz que não »." },
  { id:"q124", node:"node_3", skill:"chants", type:"order", question:"Remets ce passage dans l'ordre.", lines:["Oi sim sim sim","Oi não não não","Mas hoje tem amanhã não"], correct:["Oi sim sim sim","Oi não não não","Mas hoje tem amanhã não"], explanation:"Le refrain commence par sim/não puis annonce « aujourd'hui oui, demain non »." },
  { id:"q125", node:"node_3", skill:"chants", type:"hole", question:"Complète la ligne.", text:"Mas hoje tem amanhã {não}", holes:[{answer:"não", choices:["não","sim","iaiá","chua"]}], explanation:"La phrase oppose aujourd'hui et demain." },
  { id:"q126", node:"node_3", skill:"chants", type:"mcq", question:"Quel personnage est nommé dans le chant ?", answer:"Lampião", choices:["Lampião","Besouro","Pastinha","Bimba"], explanation:"Le chant dit « Olha a pisada de lampião »." },
  { id:"q127", node:"node_3", skill:"chants", type:"hole", question:"Complète la ligne.", text:"Mas se meu mestre disse que {sim}", holes:[{answer:"sim", choices:["sim","não","chua","maré"]}], explanation:"Le mestre dit sim dans cette phrase." },
  { id:"q128", node:"node_3", skill:"chants", type:"mcq", question:"Quelle est la réponse opposée à « Oi sim sim sim » ?", answer:"Oi não não não", choices:["Oi não não não","Sobe maré","Chuê chua","É o ABC"], explanation:"Le refrain se construit sur l'opposition sim/não." },
  { id:"q129", node:"node_3", skill:"chants", type:"order", question:"Remets l'idée du mestre dans l'ordre.", lines:["Mas se meu mestre disse que sim","Quero ver quem diz que não"], correct:["Mas se meu mestre disse que sim","Quero ver quem diz que não"], explanation:"La phrase du mestre prépare la réponse « quem diz que não »." },
  { id:"q130", node:"node_3", skill:"chants", type:"speak", question:"Parle ou chante le refrain.", prompt:"Oi sim sim sim, oi não não não", answer:"Oi sim sim sim oi não não não", accept:["Oi sim sim sim oi nao nao nao","Sim sim sim nao nao nao"], explanation:"Boa. Le contraste sim/não est le cœur du refrain." },

  { id:"q131", node:"node_4", skill:"chants", type:"hole", question:"Complète le chant « ABC ».", text:"É o A de {au}, é o B de berimbau,\nÉ o C de capoeira", holes:[{answer:"au", choices:["au","axé","Angola","aluno"]}], explanation:"Dans ce chant, A correspond à au." },
  { id:"q132", node:"node_4", skill:"chants", type:"match", question:"Associe les lettres du chant « ABC ».", pairs:[["A","Au"],["B","Berimbau"],["C","Capoeira"]], explanation:"Le refrain sert à mémoriser trois mots de base." },
  { id:"q133", node:"node_4", skill:"chants", type:"order", question:"Remets les lignes du refrain dans l'ordre.", lines:["É o A, é o B","É o A, é o B, é o C","É o A de au, é o B de berimbau","É o C de capoeira"], correct:["É o A, é o B","É o A, é o B, é o C","É o A de au, é o B de berimbau","É o C de capoeira"], explanation:"Le chant construit A, puis B, puis C." },
  { id:"q134", node:"node_4", skill:"chants", type:"mcq", question:"Dans « ABC », « Quero aprender » signifie…", answer:"Je veux apprendre", choices:["Je veux apprendre","Je sais lire","Je veux jouer vite","Je chante demain"], explanation:"Quero = je veux, aprender = apprendre." },
  { id:"q135", node:"node_4", skill:"chants", type:"hole", question:"Complète la ligne.", text:"É o B de {berimbau}", holes:[{answer:"berimbau", choices:["berimbau","batizado","Besouro","bateria"]}], explanation:"B est associé à berimbau." },
  { id:"q136", node:"node_4", skill:"chants", type:"hole", question:"Complète la ligne.", text:"É o C de {capoeira}", holes:[{answer:"capoeira", choices:["capoeira","caxixi","corrido","cabeça"]}], explanation:"C est associé à capoeira." },
  { id:"q137", node:"node_4", skill:"chants", type:"mcq", question:"Quelle phrase revient dans le chant ABC ?", answer:"Quero aprender", choices:["Quero aprender","Desce maré","Chuê chua","Olha a pisada"], explanation:"Le chant répète « Quero aprender »." },
  { id:"q138", node:"node_4", skill:"chants", type:"hole", question:"Complète la phrase.", text:"Eu não sei {ler}, yayá", holes:[{answer:"ler", choices:["ler","jogar","cantar","tocar"]}], explanation:"La ligne signifie « je ne sais pas lire »." },
  { id:"q139", node:"node_4", skill:"chants", type:"mcq", question:"Quelle séquence correspond au chant ?", answer:"A de au, B de berimbau, C de capoeira", choices:["A de au, B de berimbau, C de capoeira","A de axé, B de Bahia, C de caxixi","A de Angola, B de Bimba, C de corda","A de aluno, B de batizado, C de coro"], explanation:"Le chant associe A, B, C à trois repères." },
  { id:"q140", node:"node_4", skill:"chants", type:"speak", question:"Parle ou chante la ligne du ABC.", prompt:"É o C de capoeira", answer:"É o C de capoeira", accept:["E o C de capoeira","C de capoeira"], explanation:"Boa. C de capoeira ferme la séquence A, B, C." }
];
